apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: gitops-mgt
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-1
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 195.16.99.86
    machineGroupRef:
      kind: VSphereMachineConfig
      name: gitops-mgt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: gitops-mgt
  gitOpsRef:
    kind: FluxConfig
    name: gitops-mgt
  kubernetesVersion: "1.22"
  managementCluster: {}
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: gitops-mgt-cp
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: gitops-mgt
  namespace: default
spec:
  datacenter: SDDC-Datacenter
  insecure: false
  network: /SDDC-Datacenter/network/sddc-cgw-network-4
  server: vcenter.sddc-44-239-186-141.vmwarevmc.com
  thumbprint: A:6:6:8:B:5:C:A:7:3:7:C:0:0:2:3:7:B:7:F:6:7:9:9:3:A:B:3:1:F:8:D:A:E:9:1:0:C:7:4

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: gitops-mgt-cp
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/capv/ddjia/
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/ubuntu-kube-v1-22
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDsWSzV/Fqf6YrLdunos0sd+vE31q3Xp2e53scyxhgPoKBv+us0fxHVZHCIohKgIaTYHxM0SfaYOi1LJaXm2+XB4hEKzxSTnM5cVVFv0NG63LdwOO3HC4RfPa7eM7MFyvyWxeQ4H+1TFCufzk0y3Sun/QkXa2hOjlbdJOrIOfF1jwzBFGTCMjQTcL4LhMn7aZDkj4i3kPtKZakyeLDuAoA6GhOXPMbYbGgUkAPOLD5sO3UHbSS7oVP8bOjrtQKQ//yNZ0R6ZYJb1go14Q4R+jwPTfZ7uYstV2uYs5ifwAh+a7+Ra+st40hH6TPzVC6SuXtqNiBSgLiEM9wD4C8mEMWXZpxror2JiSEEu12EhnIMYl2VsUDKUMhc5c68EZNCWjxTMIkriQbMkxlq4121TBXdfS5ZKJTRucAaobjP7jYkEli4G38Iyg20Ns2IgGkpb4baZJkfdJki9TfmxLtsSqjH9t0C/450KKcPsdtERdVFUrr67D/I/h91MXvmFVwW4te4bGJBhHh8TuirWyvgXEjNRxZqhpL3aerkRupfhUL8ySei062LVAFj3u0trzGHU+vbKIO+QSwV0Q/8Um57DUHTB4ovjVve24BBMFjzv3435Er6OkTm/bmlBpyh/a/urVjf5hzkhAqEkO78Q1bV7q3BZX8Sz1CLGQUGc2o3SgMMSQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gitops-mgt
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/gitops-mgt
  github:
    owner: ddjjia
    personal: true
    repository: EKS-A-gitops
  systemNamespace: flux-system

---
